name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run REST controller tests
        run: npm run test-controller-rest

      - name: Start REST server and run it in background
        run: npm run start-rest &

      - name: Wait until the server is ready
        run: sleep 5

      - name: Create .env file
        run: |
          echo "BASE_URL_REST=${{ secrets.BASE_URL_REST }}" >> .env

      - name: Run REST HTTP tests
        run: npm run test-external-rest
